---
title: IBA
timezone: UTC
collections:
  cards:
    title: Cards
    output: false
    style:
      output: true
  components:
    title: Components
    output: false
    style:
      output: true
  double-cards:
    title: Double Cards
    output: false
    style:
      output: true
  menu:
    title: Menu
    output: false
    style:
      output: true
  posts:
    title: Posts
    output: true
  project-cards:
    title: Project Cards
    output: false
    style:
      output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "/"
  values:
    is_home: true
- scope:
    path: ''
    type: posts
  values:
    is_post: true
- scope:
    path: ''
    type: pages
  values:
    is_page: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
css: inline
markdown: kramdown
sass:
  style: compressed
